const {chromium}=require('D:/Temp/GPT_Temp/property-qa/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:8877',state=await (await page.request.get(base+'/api/state')).json(),money=n=>(Number(n||0)/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});await page.goto(base+'/#dashboard');await page.locator('h1').waitFor();assert.equal(await page.title(),'图图物业管家');assert.match(await page.locator('.brand').innerText(),/图图物业管家/);
 assert.match(await page.locator('main').innerText(),/应收核算/);assert.match(await page.locator('main').innerText(),/本月.*本季度.*本年度.*上年度.*近12个月.*自定义/s);assert.match(await page.locator('main').innerText(),/所选范围未收账单/);
 const currentYear=state.today.slice(0,4),yearRows=state.bills.filter(b=>b.period.startsWith(currentYear)),expectedReceivable=yearRows.reduce((n,b)=>n+b.amount,0),expectedReceived=yearRows.reduce((n,b)=>n+b.paid,0);const summary=await page.locator('.audit-summary').innerText();assert.match(summary,new RegExp(money(expectedReceivable).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(summary,new RegExp(money(expectedReceived).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
 await page.locator('[data-audit-preset="previous-year"]').click();assert.equal(await page.locator('#auditStart').inputValue(),String(Number(currentYear)-1)+'-01');assert.equal(await page.locator('#auditEnd').inputValue(),String(Number(currentYear)-1)+'-12');
 const previousUnpaid=state.bills.filter(b=>b.period.startsWith(String(Number(currentYear)-1))&&b.paid<b.amount),sample=previousUnpaid[0];if(sample){await page.locator('#auditScope').selectOption(JSON.stringify(['house',sample.house_id]));const expected=previousUnpaid.filter(b=>b.house_id===sample.house_id).length;assert.equal(await page.locator('.audit-ledger tbody tr').count(),expected)}
 await page.goto(base+'/#spaces');await page.locator('h1').waitFor();assert.match(await page.locator('main').innerText(),/车位状态与默认年度收费/);assert.equal(await page.getByRole('button',{name:/新增车位状态/}).count(),1);
 await page.goto(base+'/#fees');await page.locator('h1').waitFor();assert.match(await page.locator('main').innerText(),/整栋、整单元/);assert.doesNotMatch(await page.locator('main').innerText(),/车位状态与默认年度收费/);assert.equal(await page.getByRole('button',{name:/新增车位状态/}).count(),0);
 await page.locator('[data-act="edit"][data-kind="fees"]').click();const targets=await page.locator('[name="target_choice"] option').allTextContents();assert.ok(targets.some(x=>x.includes('整栋')));assert.ok(targets.some(x=>x.includes('整单元')));assert.ok(targets.some(x=>x.includes('车辆：')));await page.locator('[data-act="close-modal"]').first().click();
 await page.goto(base+'/#billing');await page.locator('h1').waitFor();assert.ok(await page.locator('[data-act="parking-pay"]').count()>0);assert.ok(await page.locator('[data-bill-adjust]').count()>0);assert.match(await page.locator('main').innerText(),/车位管理费/);assert.match(await page.locator('main').innerText(),/停车公共收益/);
 await page.goto(base+'/#settings');await page.locator('h1').waitFor();assert.match(await page.locator('main').innerText(),/住户身份选项/);assert.match(await page.locator('main').innerText(),/停车费到期提前提醒/);
 const stateAfter=await (await page.request.get(base+'/api/state')).json();assert.equal(state.houses.length,421);assert.equal(state.owners.length,425);assert.equal(state.vehicles.length,166);assert.equal(state.spaces.length,154);assert.equal(stateAfter.houses.length,state.houses.length);assert.equal(stateAfter.owners.length,state.owners.length);assert.equal(stateAfter.vehicles.length,state.vehicles.length);assert.equal(stateAfter.spaces.length,state.spaces.length);assert.equal(stateAfter.bills.length,state.bills.length);assert.equal(stateAfter.payments.length,state.payments.length);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: upgraded production UI and imported record counts verified; no writes performed and no browser errors.');
})().catch(e=>{console.error(e);process.exit(1)});
